-- ============================================
-- SEED DATA for LMS
-- ============================================
-- All demo/test data (Acme Corporation, fake courses, etc.) has been
-- removed from this migration in preparation for production use.
--
-- Real data should be loaded through the admin UI or dedicated
-- seed scripts configured with your organization's content.
-- ============================================
